// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
    // DIRECT_URL must point to the non-pooled Neon connection string.
    // Prisma uses this for migrations (advisory locks) while runtime queries
    // use the pooled DATABASE_URL. Without this, prisma migrate deploy fails
    // on Neon with P1002 (advisory lock timeout).
    directUrl: env('DIRECT_URL'),
  },
});
