FROM node:24-alpine

WORKDIR /app

RUN corepack enable
# Copy only manifests first for better caching
COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY prisma ./prisma
RUN pnpm prisma generate

COPY . .

EXPOSE 3000
CMD ["pnpm", "run", "start:dev"]