services:
  ajoti-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ajoti-backend-prod
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ../:/app
      - /app/node_modules
    networks:
      - app-network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/main.js
      "