services:
  ajoti-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ajoti-backend-staging
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - NODE_ENV=staging
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/prisma/seed.js &&
        node dist/src/main.js
      "