services:
  ajoti-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: ajoti-backend-dev
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - postgres
    volumes:
      - ../:/app
      - /app/node_modules
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        pnpm run start:dev
      "

